apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: "2022-04-13T03:42:47Z"
  labels:
    app: gogs
  name: gogs
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      tags: gogs,go,golang
      version: 0.11.34
    from:
      kind: DockerImage
      name: quay.io/siamaksade/gogs:0.11.34
    generation: 2
    importPolicy: {}
    name: 0.11.34
    referencePolicy:
      type: Source
