apiVersion: v1
data:
  database-name: Z29ncw==
  database-password: Z29ncw==
  database-user: Z29ncw==
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: gogs-postgresql
type: Opaque
