apiVersion: v1
imagePullSecrets:
- name: jenkins-dockercfg-xwgtx
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: jenkins
secrets:
- name: jenkins-token-6vxhv
- name: jenkins-dockercfg-xwgtx
