apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
    openshift.io/image.dockerRepositoryCheck: "2022-04-14T00:55:06Z"
  labels:
    build: test-tasks
  name: test-tasks
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: test-tasks:latest
    generation: 3
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
