apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2022-04-13T03:42:32Z"
  name: wildfly
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: openshift/wildfly-120-centos7
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
