apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2022-04-14T02:05:14Z"
  name: eap74-openjdk11-openshift-rhel8
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.4-2
    generation: 1
    importPolicy:
      insecure: true
    name: 7.4.4-2
    referencePolicy:
      type: Source
