apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmFwcHMuY2x1c3Rlci02YWIzLnNhbmRib3gxODczLm9wZW50bGMuY29tIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InJlZGhhdDEhIiwiZW1haWwiOiJoeW91QHJlZGhhdC5jb20iLCJhdXRoIjoiWVdSdGFXNDZjbVZrYUdGME1TRT0ifX19
kind: Secret
metadata:
  name: quay-cicd-secret
type: kubernetes.io/dockerconfigjson
